version: '3.8'
services:
    app:
        image: laravel:latest
        container_name: commerc_test
        volumes:
            - .:/var/www/html
        ports:
            - 8000:80
        depends_on:
            - db
    db:
        image: mysql:5.7
        container_name: commerc_test_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: commerc_test
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - 3306:3306
volumes:
    dbdata:
